imports:
  - { resource: partials/api.yml }
  - { resource: partials/service.yml }

services:
  bridge:
    class: 'Bridge'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'bridge'